// Mapping from user-friendly names to country codes
export const countryCodes = {
  "Argentina": "ar",
  "Australia": "au",
  "Austria": "at",
  "Belgium": "be",
  "Brazil": "br",
  "Bulgaria": "bg",
  "Canada": "ca",
  "China": "cn",
  "Colombia": "co",
  "Czech Republic": "cz",
  "Egypt": "eg",
  "France": "fr",
  "Germany": "de",
  "Greece": "gr",
  "Hong Kong": "hk",
  "Hungary": "hu",
  "India": "in",
  "Indonesia": "id",
  "Ireland": "ie",
  "Israel": "il",
  "Italy": "it",
  "Japan": "jp",
  "Latvia": "lv",
  "Lithuania": "lt",
  "Malaysia": "my",
  "Mexico": "mx",
  "Morocco": "ma",
  "Netherlands": "nl",
  "New Zealand": "nz",
  "Nigeria": "ng",
  "Norway": "no",
  "Philippines": "ph",
  "Poland": "pl",
  "Portugal": "pt",
  "Romania": "ro",
  "Russia": "ru",
  "Saudi Arabia": "sa",
  "Serbia": "rs",
  "Singapore": "sg",
  "Slovakia": "sk",
  "Slovenia": "si",
  "South Africa": "za",
  "South Korea": "kr",
  "Sweden": "se",
  "Switzerland": "ch",
  "Taiwan": "tw",
  "Thailand": "th",
  "Turkey": "tr",
  "UAE": "ae",
  "Ukraine": "ua",
  "United Kingdom": "gb",
  "United States": "us",
  "Venezuela": "ve",
};

// Reverse mapping from country codes to user-friendly names
export const codeToCountryName = {
  "ar": "Argentina",
  "au": "Australia",
  "at": "Austria",
  "be": "Belgium",
  "br": "Brazil",
  "bg": "Bulgaria",
  "ca": "Canada",
  "cn": "China",
  "co": "Colombia",
  "cz": "Czech Republic",
  "eg": "Egypt",
  "fr": "France",
  "de": "Germany",
  "gr": "Greece",
  "hk": "Hong Kong",
  "hu": "Hungary",
  "in": "India",
  "id": "Indonesia",
  "ie": "Ireland",
  "il": "Israel",
  "it": "Italy",
  "jp": "Japan",
  "lv": "Latvia",
  "lt": "Lithuania",
  "my": "Malaysia",
  "mx": "Mexico",
  "ma": "Morocco",
  "nl": "Netherlands",
  "nz": "New Zealand",
  "ng": "Nigeria",
  "no": "Norway",
  "ph": "Philippines",
  "pl": "Poland",
  "pt": "Portugal",
  "ro": "Romania",
  "ru": "Russia",
  "sa": "Saudi Arabia",
  "rs": "Serbia",
  "sg": "Singapore",
  "sk": "Slovakia",
  "si": "Slovenia",
  "za": "South Africa",
  "kr": "South Korea",
  "se": "Sweden",
  "ch": "Switzerland",
  "tw": "Taiwan",
  "th": "Thailand",
  "tr": "Turkey",
  "ae": "UAE",
  "ua": "Ukraine",
  "gb": "United Kingdom",
  "us": "United States",
  "ve": "Venezuela",
};
